"""activated_on user column

Revision ID: 9447b484b9df
Revises: b335a7f12062
Create Date: 2018-05-22 09:16:23.819496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9447b484b9df'
down_revision = 'b335a7f12062'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('activated_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'activated_on')
    # ### end Alembic commands ###
